"""اختبارات التقارير ببيانات وهمية؛ لا تجمع معلومات الجهاز الفعلية."""

import csv
import json
import os
import tempfile
import unittest
from pathlib import Path

os.environ.setdefault("IT_TOOLKIT_DATA_DIR", str(Path(__file__).parent / "artifacts/data"))
from src.reports.csv_report import export_csv
from src.reports.json_report import export_json
from src.reports.pdf_report import export_pdf


class ReportTests(unittest.TestCase):
    def setUp(self):
        self.data = {
            "device_name": "QA-DUMMY",
            "username": "qa-only",
            "os": {"full": "Test OS"},
            "scan_timestamp": "2026-10-02T12:00:00",
            "health_score": {
                "score": 55,
                "label": "Incomplete",
                "coverage": 50,
                "unavailable": ["Antivirus"],
            },
            "recommendations": [
                {
                    "priority": "Medium",
                    "category": "Test",
                    "recommendation": "Dummy & test <unavailable>",
                }
            ],
        }

    def test_json_round_trip_unicode(self):
        with tempfile.TemporaryDirectory() as folder:
            self.data["username"] = "مستخدم تجريبي"
            path = export_json(self.data, str(Path(folder) / "dummy.json"))
            self.assertEqual(json.loads(Path(path).read_text(encoding="utf-8")), self.data)

    def test_csv_has_limitations_and_unknown_coverage(self):
        with tempfile.TemporaryDirectory() as folder:
            path = export_csv(self.data, str(Path(folder) / "dummy.csv"))
            with open(path, encoding="utf-8-sig", newline="") as f:
                rows = list(csv.reader(f))
            self.assertIn(["Check Coverage %", "50"], rows)
            self.assertIn(["Unavailable Checks", "Antivirus"], rows)
            self.assertTrue(any("not security certification" in str(row) for row in rows))

    def test_pdf_escapes_markup_wraps_long_values_and_repeats_tables(self):
        with tempfile.TemporaryDirectory() as folder:
            self.data["os"]["full"] = "Dummy long operating system " * 35
            self.data["disks"] = [
                {"mountpoint": f"Test{i}:", "disk_type": "Dummy", "total": 100, "free": 50}
                for i in range(45)
            ]
            path = export_pdf(self.data, str(Path(folder) / "dummy.pdf"))
            self.assertTrue(Path(path).read_bytes().startswith(b"%PDF-"))
            # Qt PDF ships with the existing PySide6 dependency.
            from PySide6.QtCore import QCoreApplication
            from PySide6.QtPdf import QPdfDocument

            _app = QCoreApplication.instance() or QCoreApplication([])
            doc = QPdfDocument()
            self.assertEqual(doc.load(path), QPdfDocument.Error.None_)
            self.assertGreater(doc.pageCount(), 1)
            text = " ".join(doc.getAllText(page).text() for page in range(doc.pageCount()))
            self.assertIn("Dummy & test <unavailable>", text)
            self.assertIn("not prove security compliance", text)
            self.assertIn("Check coverage: 50%", text)
            self.assertIn("Test44:", text)
            self.assertIn("Generated by IT Operations Console", text)
            self.assertNotIn("v2.0.0", text)
            self.assertNotIn("IT Support Toolkit Pro", text)
            doc.close()
            del doc
            import gc

            gc.collect()

    def test_legacy_scan_does_not_claim_full_coverage(self):
        with tempfile.TemporaryDirectory() as folder:
            self.data["health_score"].pop("coverage")
            path = export_csv(self.data, str(Path(folder) / "legacy.csv"))
            with open(path, encoding="utf-8-sig", newline="") as f:
                rows = list(csv.reader(f))
            self.assertIn(["Check Coverage %", "Unknown"], rows)

    def test_default_export_path_is_persistent(self):
        from src.utils.app_paths import EXPORTS_DIR

        paths = [Path(export(self.data)) for export in (export_json, export_csv, export_pdf)]
        self.assertTrue(all(path.parent == EXPORTS_DIR for path in paths))
        self.assertTrue(all(path.exists() and path.stat().st_size > 0 for path in paths))


if __name__ == "__main__":
    unittest.main(verbosity=2)
